name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}   # DockerHub token (read,write,delete access)

    - name: Build Docker image
      run: |
        docker build -t rohan531113/grampanchayat-new:latest .

    - name: Push Docker image
      run: |
        docker push rohan531113/grampanchayat-new:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}          # EC2 public IP
        username: ${{ secrets.SERVER_USER }}    # ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}      # .pem private key
        script: |
          cd /home/ubuntu/Grampanchayat-new
          docker-compose pull
          docker-compose down
          docker-compose up -d
